- name: Install and run Docker container 
  hosts: webservers 
  become: yes 
  
  tasks: 
   - name: Install Docker 
     apt: 
       update_cache: yes 
       name: docker.io 
   
   - name: Install pip 
     apt: 
       name: python3-pip 

   - name: Install docker module 
     pip: 
       name: docker 

                 
